export default {
    SerialPort: Symbol.for('SerialPort'),
    Hw: Symbol.for('Hw'),
    Hid: Symbol.for('Hid'),
    Context: Symbol.for('Context'),
    Window: Symbol.for('Window'),
    Menu: Symbol.for('MenuService'),
    Native: Symbol.for('Native'),
    NotificationService: Symbol.for('NotificationService'),
    Preferences: Symbol.for('Preferences'),
    SystemPreference: Symbol.for('SystemPreference'),
    ThemeService: Symbol.for('ThemeService'),
    Updater: Symbol.for('Updater'),
    View: Symbol.for('View'),
}
